// Test definitions. Do NOT edit this file!
#define CATCH_CONFIG_MAIN
#include "catch.hpp"
#include "main.hpp"

// ─────────────────────────────────────────────────────────────────────────────
// [T1]  makeVector() — fills with random integers in [0, 20), sorted
// ─────────────────────────────────────────────────────────────────────────────

TEST_CASE("T1a: makeVector fills 10 elements all in [0, 20)", "[T1]")
{
    srand(0);
    vector<int> number(10);
    makeVector(number);
    REQUIRE(number.size() == 10);
    for (int v : number)
    {
        REQUIRE(v >= 0);
        REQUIRE(v < 20);
    }
}

TEST_CASE("T1b: makeVector returns the vector in non-decreasing order", "[T1]")
{
    srand(42);
    vector<int> number(10);
    makeVector(number);
    for (size_t i = 1; i < number.size(); i++)
        REQUIRE(number[i - 1] <= number[i]);
}

// ─────────────────────────────────────────────────────────────────────────────
// [T2]  insertVector() — inserts while preserving sorted order
// ─────────────────────────────────────────────────────────────────────────────

TEST_CASE("T2a: insertVector places value at correct sorted position", "[T2]")
{
    vector<int> v = {1, 3, 5, 7, 9};
    insertVector(v, 4);
    REQUIRE(v.size() == 6);
    vector<int> exp = {1, 3, 4, 5, 7, 9};
    REQUIRE(v == exp);
}

TEST_CASE("T2b: insertVector appends at end when value larger than all", "[T2]")
{
    vector<int> v = {1, 3, 5, 7, 9};
    insertVector(v, 100);
    REQUIRE(v.size() == 6);
    REQUIRE(v.back() == 100);
    // still sorted
    for (size_t i = 1; i < v.size(); i++)
        REQUIRE(v[i - 1] <= v[i]);
}

// ─────────────────────────────────────────────────────────────────────────────
// [T3]  deleteVector() — erases all occurrences, return count or -1 if absent
// ─────────────────────────────────────────────────────────────────────────────

TEST_CASE("T3a: deleteVector removes all occurrences and returns the count", "[T3]")
{
    vector<int> v = {1, 2, 3, 2, 4, 2, 5};
    int erased = deleteVector(v, 2);
    REQUIRE(erased == 3);
    vector<int> exp = {1, 3, 4, 5};
    REQUIRE(v == exp);
}

TEST_CASE("T3b: deleteVector returns -1 when value is not present", "[T3]")
{
    vector<int> v = {1, 2, 3, 4, 5};
    int erased = deleteVector(v, 99);
    REQUIRE(erased == -1);
    // unchanged
    vector<int> exp = {1, 2, 3, 4, 5};
    REQUIRE(v == exp);
}

// ─────────────────────────────────────────────────────────────────────────────
// [T4]  Integration — insertVector keeps sort, deleteVector restores
// ─────────────────────────────────────────────────────────────────────────────

TEST_CASE("T4a: insertVector then deleteVector restores original (1 occurrence)", "[T4]")
{
    vector<int> orig = {2, 4, 6, 8, 10};
    vector<int> v = orig;
    insertVector(v, 5);
    REQUIRE(v.size() == 6);
    int erased = deleteVector(v, 5);
    REQUIRE(erased == 1);
    REQUIRE(v == orig);
}

TEST_CASE("T4b: deleteVector on single-element vector — found vs not found", "[T4]")
{
    vector<int> v1 = {7};
    REQUIRE(deleteVector(v1, 7) == 1);
    REQUIRE(v1.empty());

    vector<int> v2 = {7};
    REQUIRE(deleteVector(v2, 8) == -1);
    REQUIRE(v2.size() == 1);
}
